// <auto-generated />
using System;
using LuckyDrawPromotion.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuckyDrawPromotion.Migrations
{
    [DbContext(typeof(LuckyDrawPromotionContext))]
    partial class LuckyDrawPromotionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LuckyDrawPromotion.Models.Campaign", b =>
                {
                    b.Property<int>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampaignId"), 1L, 1);

                    b.Property<bool>("ApplyAllCampaign")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoUpdate")
                        .HasColumnType("bit");

                    b.Property<int>("CharsetId")
                        .HasColumnType("int");

                    b.Property<int>("CodeCount")
                        .HasColumnType("int");

                    b.Property<int>("CodeLength")
                        .HasColumnType("int");

                    b.Property<int>("CodeUsageLimit")
                        .HasColumnType("int");

                    b.Property<bool>("CustomerJoinOnlyOne")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time(0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postfix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SizeProgramId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(0)");

                    b.Property<bool>("Unlimited")
                        .HasColumnType("bit");

                    b.HasKey("CampaignId");

                    b.HasIndex("CharsetId");

                    b.HasIndex("SizeProgramId");

                    b.ToTable("Campaigns");

                    b.HasData(
                        new
                        {
                            CampaignId = 1,
                            ApplyAllCampaign = false,
                            AutoUpdate = true,
                            CharsetId = 1,
                            CodeCount = 50,
                            CodeLength = 10,
                            CodeUsageLimit = 1,
                            CustomerJoinOnlyOne = false,
                            Description = "Description Lucky Draw 1",
                            EndDate = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            Name = "Lucky Draw 1",
                            Postfix = "",
                            Prefix = "ALTA",
                            SizeProgramId = 1,
                            StartDate = new DateTime(2020, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new TimeSpan(0, 13, 0, 0, 0),
                            Unlimited = false
                        });
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.CampaignGift", b =>
                {
                    b.Property<int>("CampaignGiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampaignGiftId"), 1L, 1);

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("GiftCodeCount")
                        .HasColumnType("int");

                    b.Property<int>("GiftId")
                        .HasColumnType("int");

                    b.HasKey("CampaignGiftId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("GiftId");

                    b.ToTable("CampaignGifts");

                    b.HasData(
                        new
                        {
                            CampaignGiftId = 1,
                            CampaignId = 1,
                            GiftCodeCount = 15,
                            GiftId = 1
                        },
                        new
                        {
                            CampaignGiftId = 2,
                            CampaignId = 1,
                            GiftCodeCount = 10,
                            GiftId = 2
                        });
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.Charset", b =>
                {
                    b.Property<int>("CharsetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharsetId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CharsetId");

                    b.ToTable("Charsets");

                    b.HasData(
                        new
                        {
                            CharsetId = 1,
                            Name = "Numbers",
                            Value = "123456789"
                        });
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.CodeCampaign", b =>
                {
                    b.Property<int>("CodeCampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeCampaignId"), 1L, 1);

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CodeCampaignId");

                    b.HasIndex("CampaignId");

                    b.ToTable("CodeCampaigns");

                    b.HasData(
                        new
                        {
                            CodeCampaignId = 1,
                            CampaignId = 1,
                            Code = "ALTAIKJ40B",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 2,
                            CampaignId = 1,
                            Code = "ALTAFM P3V8",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 3,
                            CampaignId = 1,
                            Code = "ALTA1ES0G4",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 4,
                            CampaignId = 1,
                            Code = "ALTA30PZTA",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 5,
                            CampaignId = 1,
                            Code = "ALTAYLZ1RZ",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 6,
                            CampaignId = 1,
                            Code = "ALTAEWLKDO",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 7,
                            CampaignId = 1,
                            Code = "ALTAVACIW0",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 8,
                            CampaignId = 1,
                            Code = "ALTATM C76Q",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 9,
                            CampaignId = 1,
                            Code = "ALTAPBO6GN",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 10,
                            CampaignId = 1,
                            Code = "ALTARSVPZP",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 11,
                            CampaignId = 1,
                            Code = "ALTA7GNKYS",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 12,
                            CampaignId = 1,
                            Code = "ALTAYM IC2A",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 13,
                            CampaignId = 1,
                            Code = "ALTATS53ZH",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 14,
                            CampaignId = 1,
                            Code = "ALTA0JSERO",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 15,
                            CampaignId = 1,
                            Code = "ALTAIVJOEK",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 16,
                            CampaignId = 1,
                            Code = "ALTA85NDG8",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 17,
                            CampaignId = 1,
                            Code = "ALTAZIIM K1",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 18,
                            CampaignId = 1,
                            Code = "ALTA4KN2RC",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 19,
                            CampaignId = 1,
                            Code = "ALTA3P6DKK",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 20,
                            CampaignId = 1,
                            Code = "ALTAM BHL1O",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 21,
                            CampaignId = 1,
                            Code = "ALTA4NYKVB",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 22,
                            CampaignId = 1,
                            Code = "ALTA3BYGRO",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 23,
                            CampaignId = 1,
                            Code = "ALTAIGTGT7",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 24,
                            CampaignId = 1,
                            Code = "ALTAAY6T6H",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 25,
                            CampaignId = 1,
                            Code = "ALTAVCLJ04",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 26,
                            CampaignId = 1,
                            Code = "ALTA8OYHCC",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 27,
                            CampaignId = 1,
                            Code = "ALTAZSFWGA",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 28,
                            CampaignId = 1,
                            Code = "ALTAIVM 1P4",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 29,
                            CampaignId = 1,
                            Code = "ALTAJB5084",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 30,
                            CampaignId = 1,
                            Code = "ALTADQBRE2",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 31,
                            CampaignId = 1,
                            Code = "ALTAN4Q8J2",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 32,
                            CampaignId = 1,
                            Code = "ALTAFJSKRA",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 33,
                            CampaignId = 1,
                            Code = "ALTAIR6KWQ",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 34,
                            CampaignId = 1,
                            Code = "ALTAG5N0Z7",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 35,
                            CampaignId = 1,
                            Code = "ALTA8Q4IA2",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 36,
                            CampaignId = 1,
                            Code = "ALTA8CH1LP",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 37,
                            CampaignId = 1,
                            Code = "ALTAZERKID",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 38,
                            CampaignId = 1,
                            Code = "ALTA44ZJPO",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 39,
                            CampaignId = 1,
                            Code = "ALTAGRKSJB",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 40,
                            CampaignId = 1,
                            Code = "ALTAOYG8TS",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 41,
                            CampaignId = 1,
                            Code = "ALTAKN3CTS",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 42,
                            CampaignId = 1,
                            Code = "ALTA1773M 1",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 43,
                            CampaignId = 1,
                            Code = "ALTARTZQ8V",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 44,
                            CampaignId = 1,
                            Code = "ALTAFLQJVF",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 45,
                            CampaignId = 1,
                            Code = "ALTA118SVA",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 46,
                            CampaignId = 1,
                            Code = "ALTANFBODT",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 47,
                            CampaignId = 1,
                            Code = "ALTAPVM R5O",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 48,
                            CampaignId = 1,
                            Code = "ALTA2OG1PG",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 49,
                            CampaignId = 1,
                            Code = "ALTATNO7E4",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeCampaignId = 50,
                            CampaignId = 1,
                            Code = "ALTA1A8GH0",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.CodeGiftCampaign", b =>
                {
                    b.Property<int>("CodeGiftCampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeGiftCampaignId"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("CampaignGiftId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CodeGiftCampaignId");

                    b.HasIndex("CampaignGiftId");

                    b.ToTable("CodeGiftCampaigns");

                    b.HasData(
                        new
                        {
                            CodeGiftCampaignId = 1,
                            Active = true,
                            CampaignGiftId = 1,
                            Code = "GIF147DIKA3QJY",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeGiftCampaignId = 2,
                            Active = true,
                            CampaignGiftId = 1,
                            Code = "GIF2VH8BFI58CW",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeGiftCampaignId = 3,
                            Active = true,
                            CampaignGiftId = 1,
                            Code = "GIF3QES2J6SD8Z",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeGiftCampaignId = 4,
                            Active = true,
                            CampaignGiftId = 1,
                            Code = "GIF4M 6QJM M PHTL",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeGiftCampaignId = 5,
                            Active = true,
                            CampaignGiftId = 1,
                            Code = "GIF58JPAGBH143",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeGiftCampaignId = 6,
                            Active = true,
                            CampaignGiftId = 1,
                            Code = "GIF66QIZTGFTL8",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeGiftCampaignId = 7,
                            Active = true,
                            CampaignGiftId = 1,
                            Code = "GIF727RJ3EBBRJ",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeGiftCampaignId = 8,
                            Active = true,
                            CampaignGiftId = 1,
                            Code = "GIF8ID6RVH3QIA",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeGiftCampaignId = 9,
                            Active = true,
                            CampaignGiftId = 1,
                            Code = "GIF912VHOIEY2T",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeGiftCampaignId = 10,
                            Active = true,
                            CampaignGiftId = 1,
                            Code = "GIF10RHAGQDJVCT",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeGiftCampaignId = 11,
                            Active = true,
                            CampaignGiftId = 1,
                            Code = "GIF11S6EHSCE4O1",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeGiftCampaignId = 12,
                            Active = true,
                            CampaignGiftId = 1,
                            Code = "GIF12WVWWGE1K1G",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeGiftCampaignId = 13,
                            Active = true,
                            CampaignGiftId = 1,
                            Code = "GIF13RZ0JS2F41H",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeGiftCampaignId = 14,
                            Active = true,
                            CampaignGiftId = 1,
                            Code = "GIF144VTJ8WB10T",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeGiftCampaignId = 15,
                            Active = true,
                            CampaignGiftId = 1,
                            Code = "GIF15YC5C1M 20BT",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeGiftCampaignId = 16,
                            Active = true,
                            CampaignGiftId = 2,
                            Code = "GIF16ADZB4LFPVY",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeGiftCampaignId = 17,
                            Active = true,
                            CampaignGiftId = 2,
                            Code = "GIF17F8M OFNI6K5",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeGiftCampaignId = 18,
                            Active = true,
                            CampaignGiftId = 2,
                            Code = "GIF18R1AF8SE2FB",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeGiftCampaignId = 19,
                            Active = true,
                            CampaignGiftId = 2,
                            Code = "GIF192WZI4GFHC3",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeGiftCampaignId = 20,
                            Active = true,
                            CampaignGiftId = 2,
                            Code = "GIF20JZQE4ASPRC",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeGiftCampaignId = 21,
                            Active = true,
                            CampaignGiftId = 2,
                            Code = "GIF21CCPHGB0E0L",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeGiftCampaignId = 22,
                            Active = true,
                            CampaignGiftId = 2,
                            Code = "GIF22K3DSPM QDIE",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeGiftCampaignId = 23,
                            Active = true,
                            CampaignGiftId = 2,
                            Code = "GIF23P6BSITS8HR",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeGiftCampaignId = 24,
                            Active = true,
                            CampaignGiftId = 2,
                            Code = "GIF24OQ45QJG6I2",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodeGiftCampaignId = 25,
                            Active = true,
                            CampaignGiftId = 2,
                            Code = "GIF25RVQK623HT2",
                            CreatedDate = new DateTime(2020, 2, 24, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<bool>("Block")
                        .HasColumnType("bit");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("PositionId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Block = false,
                            CustomerAddress = "Quận 1, TP.HCM",
                            CustomerName = "Nguyễn Văn A",
                            CustomerPhone = "0987654321",
                            DateOfBirth = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PositionId = 1
                        },
                        new
                        {
                            CustomerId = 2,
                            Block = false,
                            CustomerAddress = "Quận 2, TP.HCM",
                            CustomerName = "Nguyễn Văn B",
                            CustomerPhone = "0987654322",
                            DateOfBirth = new DateTime(2000, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PositionId = 2
                        },
                        new
                        {
                            CustomerId = 3,
                            Block = false,
                            CustomerAddress = "Quận 11, TP.HCM",
                            CustomerName = "Nguyễn Văn C",
                            CustomerPhone = "0987654311",
                            DateOfBirth = new DateTime(2000, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PositionId = 11
                        });
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.Gift", b =>
                {
                    b.Property<int>("GiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GiftId"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GiftId");

                    b.ToTable("Gifts");

                    b.HasData(
                        new
                        {
                            GiftId = 1,
                            CreatedDate = new DateTime(2022, 5, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hạt nêm Knnor Chay Nấm Hương 400g",
                            Name = "Hạt nêm Knnor Chay Nấm Hương 400g"
                        },
                        new
                        {
                            GiftId = 2,
                            CreatedDate = new DateTime(2022, 5, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hạt nêm Knnor Từ Thịt Thăn, Xương Ống & Tủy 600g",
                            Name = "Hạt nêm Knnor Từ Thịt Thăn, Xương Ống & Tủy 600g"
                        },
                        new
                        {
                            GiftId = 3,
                            CreatedDate = new DateTime(2022, 5, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gia vị Hoàn Chỉnh Knnor Canh Chua 30g",
                            Name = "Gia vị Hoàn Chỉnh Knnor Canh Chua 30g"
                        },
                        new
                        {
                            GiftId = 4,
                            CreatedDate = new DateTime(2022, 5, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Xốt nêm Đậm Đặc Knnor Từ Vị Thịt Heo 240g",
                            Name = "Xốt nêm Đậm Đặc Knnor Từ Vị Thịt Heo 240g"
                        },
                        new
                        {
                            GiftId = 5,
                            CreatedDate = new DateTime(2022, 5, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hạt nêm Knnor Từ Thịt Thăn, Xương Ống & Tủy 900g",
                            Name = "Hạt nêm Knnor Từ Thịt Thăn, Xương Ống & Tủy 900g"
                        },
                        new
                        {
                            GiftId = 6,
                            CreatedDate = new DateTime(2022, 5, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Knnor Natural Bột Nêm Tự Nhiên Vị Rau Cũ 150g",
                            Name = "Knnor Natural Bột Nêm Tự Nhiên Vị Rau Cũ 150g"
                        });
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeOfBussinessId")
                        .HasColumnType("int");

                    b.HasKey("PositionId");

                    b.HasIndex("TypeOfBussinessId");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            PositionId = 1,
                            Name = "Chủ",
                            TypeOfBussinessId = 1
                        },
                        new
                        {
                            PositionId = 2,
                            Name = "Quản lý",
                            TypeOfBussinessId = 1
                        },
                        new
                        {
                            PositionId = 3,
                            Name = "Chủ",
                            TypeOfBussinessId = 2
                        },
                        new
                        {
                            PositionId = 4,
                            Name = "Quản lý",
                            TypeOfBussinessId = 2
                        },
                        new
                        {
                            PositionId = 5,
                            Name = "Chủ",
                            TypeOfBussinessId = 3
                        },
                        new
                        {
                            PositionId = 6,
                            Name = "Quản lý",
                            TypeOfBussinessId = 3
                        },
                        new
                        {
                            PositionId = 7,
                            Name = "Chủ",
                            TypeOfBussinessId = 4
                        },
                        new
                        {
                            PositionId = 8,
                            Name = "Quản lý",
                            TypeOfBussinessId = 4
                        },
                        new
                        {
                            PositionId = 9,
                            Name = "Chủ",
                            TypeOfBussinessId = 5
                        },
                        new
                        {
                            PositionId = 10,
                            Name = "Quản lý",
                            TypeOfBussinessId = 5
                        },
                        new
                        {
                            PositionId = 11,
                            Name = "Bếp",
                            TypeOfBussinessId = 3
                        });
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.RepeatSchedule", b =>
                {
                    b.Property<int>("RepeatScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepeatScheduleId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RepeatScheduleId");

                    b.ToTable("RepeatSchedules");

                    b.HasData(
                        new
                        {
                            RepeatScheduleId = 1,
                            Name = "Monthly on day"
                        },
                        new
                        {
                            RepeatScheduleId = 2,
                            Name = "Weekly on day"
                        },
                        new
                        {
                            RepeatScheduleId = 3,
                            Name = "Repeat daily"
                        });
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.Rule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleId"), 1L, 1);

                    b.Property<bool>("AllDay")
                        .HasColumnType("bit");

                    b.Property<int>("CampainGiftId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("GiftAmount")
                        .HasColumnType("int");

                    b.Property<int>("Probability")
                        .HasColumnType("int");

                    b.Property<int>("RepeatScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScheduleValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("RuleId");

                    b.HasIndex("CampainGiftId");

                    b.HasIndex("RepeatScheduleId");

                    b.ToTable("Rules");

                    b.HasData(
                        new
                        {
                            RuleId = 1,
                            AllDay = false,
                            CampainGiftId = 1,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            GiftAmount = 10,
                            Probability = 20,
                            RepeatScheduleId = 1,
                            RuleName = "Monthly",
                            ScheduleValue = "1, 15",
                            StartTime = new TimeSpan(0, 15, 0, 0, 0)
                        },
                        new
                        {
                            RuleId = 2,
                            AllDay = false,
                            CampainGiftId = 1,
                            GiftAmount = 10,
                            Probability = 10,
                            RepeatScheduleId = 2,
                            RuleName = "Weekly",
                            ScheduleValue = "Mon, Thu",
                            StartTime = new TimeSpan(0, 15, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.ScannedOrSpin", b =>
                {
                    b.Property<int>("ScannedOrSpinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScannedOrSpinId"), 1L, 1);

                    b.Property<int>("CodeCampaignId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScannedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SpinDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ScannedOrSpinId");

                    b.HasIndex("CodeCampaignId");

                    b.HasIndex("CustomerId");

                    b.ToTable("ScannedOrSpins");

                    b.HasData(
                        new
                        {
                            ScannedOrSpinId = 1,
                            CodeCampaignId = 1,
                            CustomerId = 1,
                            ScannedDate = new DateTime(2020, 3, 1, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            SpinDate = new DateTime(2020, 3, 1, 16, 1, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScannedOrSpinId = 2,
                            CodeCampaignId = 1,
                            CustomerId = 1,
                            ScannedDate = new DateTime(2020, 3, 1, 16, 2, 0, 0, DateTimeKind.Unspecified),
                            SpinDate = new DateTime(2020, 3, 1, 16, 3, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScannedOrSpinId = 3,
                            CodeCampaignId = 1,
                            CustomerId = 1,
                            ScannedDate = new DateTime(2020, 3, 1, 16, 4, 0, 0, DateTimeKind.Unspecified),
                            SpinDate = new DateTime(2020, 3, 1, 16, 5, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScannedOrSpinId = 4,
                            CodeCampaignId = 1,
                            CustomerId = 2,
                            ScannedDate = new DateTime(2020, 3, 1, 16, 5, 0, 0, DateTimeKind.Unspecified),
                            SpinDate = new DateTime(2020, 3, 1, 16, 6, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScannedOrSpinId = 5,
                            CodeCampaignId = 1,
                            CustomerId = 2,
                            ScannedDate = new DateTime(2020, 3, 1, 16, 8, 0, 0, DateTimeKind.Unspecified),
                            SpinDate = new DateTime(2020, 3, 1, 16, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScannedOrSpinId = 6,
                            CodeCampaignId = 1,
                            CustomerId = 3,
                            ScannedDate = new DateTime(2020, 3, 1, 16, 1, 0, 0, DateTimeKind.Unspecified),
                            SpinDate = new DateTime(2020, 3, 1, 16, 3, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.SizeProgram", b =>
                {
                    b.Property<int>("SizeProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SizeProgramId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SizeProgramId");

                    b.ToTable("SizePrograms");

                    b.HasData(
                        new
                        {
                            SizeProgramId = 1,
                            Description = "up to thounsands of random discount codes designed for single use by a limited group customers (e.g., \"ACME-5P13R\" gives $25 off for the dirst 3 purches, new customers from Warsaw only).",
                            Name = "Bulk codes"
                        },
                        new
                        {
                            SizeProgramId = 2,
                            Description = "A fixed-code discount designed for mutiple uses (e.g., 10% of with \"blackfriday\" code)",
                            Name = "Standalone code"
                        });
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.TypeOfBussiness", b =>
                {
                    b.Property<int>("TypeOfBussinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeOfBussinessId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeOfBussinessId");

                    b.ToTable("TypeOfBussiness");

                    b.HasData(
                        new
                        {
                            TypeOfBussinessId = 1,
                            Name = "Khách sạn"
                        },
                        new
                        {
                            TypeOfBussinessId = 2,
                            Name = "Nhà hàng"
                        },
                        new
                        {
                            TypeOfBussinessId = 3,
                            Name = "Quán ăn"
                        },
                        new
                        {
                            TypeOfBussinessId = 4,
                            Name = "Bán sỉ"
                        },
                        new
                        {
                            TypeOfBussinessId = 5,
                            Name = "Resort"
                        });
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin0@gmail.com",
                            Password = "Aa12345"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "admin1@gmail.com",
                            Password = "Aa12345"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "admin2@gmail.com",
                            Password = "Aa12345"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "admin3@gmail.com",
                            Password = "Aa12345"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "admin4@gmail.com",
                            Password = "Aa12345"
                        });
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.Winner", b =>
                {
                    b.Property<int>("WinnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WinnerId"), 1L, 1);

                    b.Property<string>("AddressReceivedGift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodeGiftCampaignId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("SentGift")
                        .HasColumnType("bit");

                    b.Property<DateTime>("WinDate")
                        .HasColumnType("datetime2");

                    b.HasKey("WinnerId");

                    b.HasIndex("CodeGiftCampaignId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Winners");

                    b.HasData(
                        new
                        {
                            WinnerId = 1,
                            AddressReceivedGift = "Quận 1, TP.HCM",
                            CodeGiftCampaignId = 1,
                            CustomerId = 1,
                            SentGift = true,
                            WinDate = new DateTime(2020, 3, 1, 16, 5, 30, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            WinnerId = 2,
                            AddressReceivedGift = "Quận 2, TP.HCM",
                            CodeGiftCampaignId = 2,
                            CustomerId = 2,
                            SentGift = true,
                            WinDate = new DateTime(2020, 3, 1, 16, 6, 30, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            WinnerId = 3,
                            AddressReceivedGift = "Quận 2, TP.HCM",
                            CodeGiftCampaignId = 16,
                            CustomerId = 2,
                            SentGift = true,
                            WinDate = new DateTime(2020, 3, 1, 16, 10, 30, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.Campaign", b =>
                {
                    b.HasOne("LuckyDrawPromotion.Models.Charset", "Charset")
                        .WithMany("Campaigns")
                        .HasForeignKey("CharsetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuckyDrawPromotion.Models.SizeProgram", "SizeProgram")
                        .WithMany("Campaigns")
                        .HasForeignKey("SizeProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Charset");

                    b.Navigation("SizeProgram");
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.CampaignGift", b =>
                {
                    b.HasOne("LuckyDrawPromotion.Models.Campaign", "Campaign")
                        .WithMany("CampaignGifts")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuckyDrawPromotion.Models.Gift", "Gift")
                        .WithMany("CampaignGifts")
                        .HasForeignKey("GiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Gift");
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.CodeCampaign", b =>
                {
                    b.HasOne("LuckyDrawPromotion.Models.Campaign", "Campaign")
                        .WithMany("CodeCampaigns")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.CodeGiftCampaign", b =>
                {
                    b.HasOne("LuckyDrawPromotion.Models.CampaignGift", "CampaignGift")
                        .WithMany("CodeGiftCampaigns")
                        .HasForeignKey("CampaignGiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CampaignGift");
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.Customer", b =>
                {
                    b.HasOne("LuckyDrawPromotion.Models.Position", "Position")
                        .WithMany("Customers")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.Position", b =>
                {
                    b.HasOne("LuckyDrawPromotion.Models.TypeOfBussiness", "TypeOfBussiness")
                        .WithMany("Positions")
                        .HasForeignKey("TypeOfBussinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TypeOfBussiness");
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.Rule", b =>
                {
                    b.HasOne("LuckyDrawPromotion.Models.CampaignGift", "CampaignGift")
                        .WithMany("Rules")
                        .HasForeignKey("CampainGiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuckyDrawPromotion.Models.RepeatSchedule", "RepeatSchedule")
                        .WithMany("Rules")
                        .HasForeignKey("RepeatScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CampaignGift");

                    b.Navigation("RepeatSchedule");
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.ScannedOrSpin", b =>
                {
                    b.HasOne("LuckyDrawPromotion.Models.CodeCampaign", "CodeCampaign")
                        .WithMany("ScannedOrSpins")
                        .HasForeignKey("CodeCampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuckyDrawPromotion.Models.Customer", "Customer")
                        .WithMany("ScannedOrSpins")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CodeCampaign");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.Winner", b =>
                {
                    b.HasOne("LuckyDrawPromotion.Models.CodeGiftCampaign", "CodeGiftCampaign")
                        .WithMany("Winners")
                        .HasForeignKey("CodeGiftCampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuckyDrawPromotion.Models.Customer", "Customer")
                        .WithMany("Winners")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CodeGiftCampaign");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.Campaign", b =>
                {
                    b.Navigation("CampaignGifts");

                    b.Navigation("CodeCampaigns");
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.CampaignGift", b =>
                {
                    b.Navigation("CodeGiftCampaigns");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.Charset", b =>
                {
                    b.Navigation("Campaigns");
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.CodeCampaign", b =>
                {
                    b.Navigation("ScannedOrSpins");
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.CodeGiftCampaign", b =>
                {
                    b.Navigation("Winners");
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.Customer", b =>
                {
                    b.Navigation("ScannedOrSpins");

                    b.Navigation("Winners");
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.Gift", b =>
                {
                    b.Navigation("CampaignGifts");
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.Position", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.RepeatSchedule", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.SizeProgram", b =>
                {
                    b.Navigation("Campaigns");
                });

            modelBuilder.Entity("LuckyDrawPromotion.Models.TypeOfBussiness", b =>
                {
                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
